{% set name = "nccl" %}
{% set version = "2.23.4-1" %}

package:
  name: {{ name|lower }}
  version: {{ version|replace("-", ".") }}

source:
  url: https://github.com/NVIDIA/nccl/archive/v{{ version }}.tar.gz
  sha256: 6b946b70a9d2d01871842cbd15ec56488d358abe9a0f3767e372fddc3e241ba7
  patches:
    - 0002-use-conda-ar-not-system.patch

build:
  number: 1
  skip: true  # [(not linux) or cuda_compiler_version in (undefined, "None", "10.2")]
  ignore_run_exports_from:
    # Ignore `cudatoolkit` dependency in CUDA 11 builds
    - {{ compiler("cuda") }}  # [(cuda_compiler_version or "").startswith("11")]
  run_exports:
    # xref: https://github.com/NVIDIA/nccl/issues/218
    - {{ pin_subpackage(name, max_pin="x") }}

requirements:
  build:
    - {{ compiler("c") }}
    - {{ stdlib("c") }}
    - {{ compiler("cxx") }}
    - {{ compiler("cuda") }}
    - {{ stdlib("c") }}
    - make
  host:
    - cuda-version ={{ cuda_compiler_version }}          # [(cuda_compiler_version or "").startswith("11")]
  run:
    - cuda-version >=12.0,<13.0a0  # [(cuda_compiler_version or "").startswith("12")]
    - cuda-version >=11.0,<12.0a0  # [(cuda_compiler_version or "").startswith("11")]

test:
  commands:
    - test -f "${PREFIX}/include/nccl.h"
    - test -f "${PREFIX}/lib/libnccl.so"
    - test ! -f "${PREFIX}/lib/libnccl_static.a"

about:
  home: https://developer.nvidia.com/nccl
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Optimized primitives for collective multi-GPU communication

  description: |
    The NVIDIA Collective Communications Library (NCCL) implements multi-GPU
    and multi-node collective communication primitives that are performance
    optimized for NVIDIA GPUs. NCCL provides routines such as all-gather,
    all-reduce, broadcast, reduce, reduce-scatter, that are optimized to
    achieve high bandwidth over PCIe and NVLink high-speed interconnect.

  doc_url: https://docs.nvidia.com/deeplearning/sdk/nccl-developer-guide/docs/index.html
  dev_url: https://github.com/NVIDIA/nccl

extra:
  recipe-maintainers:
    - conda-forge/cuda
    - jakirkham
    - leofang
